"""HTML report generation for Wai."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional

import numpy as np
import pandas as pd


_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Wai &mdash; {station_id} Report</title>
  <style>
    * {{ box-sizing: border-box; }}
    body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 32px 48px; color: #222; background: #fafbfc; }}
    h1 {{ color: #1a5276; margin-bottom: 4px; }}
    h2 {{ color: #1f618d; border-bottom: 2px solid #aed6f1; padding-bottom: 6px; margin-top: 32px; }}
    .subtitle {{ color: #555; font-size: 0.95em; margin-top: 0; }}
    .disclaimer {{ background: #fef9e7; border: 1px solid #f0d060; padding: 12px 16px; border-radius: 6px; margin: 16px 0; font-size: 0.9em; }}
    .grid3 {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 20px 0; }}
    .card {{ background: #eaf4fb; border-radius: 10px; padding: 20px; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,0.08); }}
    .card-val {{ font-size: 2em; font-weight: 700; color: #1a5276; }}
    .card-lbl {{ font-size: 0.8em; color: #555; margin-top: 4px; }}
    table {{ border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 0.93em; }}
    th {{ background: #1f618d; color: #fff; padding: 9px 14px; text-align: left; }}
    td {{ border: 1px solid #dde; padding: 8px 14px; }}
    tr:nth-child(even) td {{ background: #f0f8ff; }}
    .anomaly-box {{ background: #fef9e7; border-left: 5px solid #f39c12; padding: 14px 18px; border-radius: 4px; margin: 12px 0; }}
    .footer {{ font-size: 0.8em; color: #999; margin-top: 48px; padding-top: 12px; border-top: 1px solid #ddd; }}
  </style>
</head>
<body>
  <h1>Wai Coastal Water-Level Report</h1>
  <p class="subtitle">Reproducible pipeline &bull; Time-series forecasting &bull; NOAA-aware</p>
  <div class="disclaimer">
    <strong>Data notice:</strong> This report is generated from <strong>DEMO_SYNTHETIC</strong> data only.
    No private sensor data, credentials, or proprietary Hohonu information is included.
  </div>

  <h2>Station Summary</h2>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Station ID</td><td>{station_id}</td></tr>
    <tr><td>Source</td><td>{source}</td></tr>
    <tr><td>Date Range</td><td>{date_range}</td></tr>
    <tr><td>Datum</td><td>{datum}</td></tr>
    <tr><td>Units</td><td>{units}</td></tr>
    <tr><td>Location (lat, lon)</td><td>{lat}, {lon}</td></tr>
    <tr><td>Total Observations</td><td>{n_obs:,}</td></tr>
    <tr><td>Threshold Mode</td><td>{threshold_mode}</td></tr>
    <tr><td>Alert Threshold</td><td>{high_water_threshold}</td></tr>
    <tr><td>Threshold Source</td><td>{threshold_source}</td></tr>
    <tr><td>Threshold Reference Range</td><td>{threshold_reference_range}</td></tr>
  </table>

  <h2>Water-Level Statistics</h2>
  <div class="grid3">
    <div class="card"><div class="card-val">{wl_mean}</div><div class="card-lbl">Mean (m)</div></div>
    <div class="card"><div class="card-val">{wl_max}</div><div class="card-lbl">Max (m)</div></div>
    <div class="card"><div class="card-val">{wl_min}</div><div class="card-lbl">Min (m)</div></div>
  </div>

  <h2>Forecast Performance</h2>
  {metrics_section}

  <h2>High-Water / Anomaly Events</h2>
  <div class="anomaly-box">
    {anomaly_html}
  </div>

  <h2>Trend Notes</h2>
  <p>{trend_note}</p>

  <div class="footer">
    Generated by <strong>Wai</strong> on {generated_at} &bull;
    Data: DEMO (synthetic) &bull;
    <a href="https://github.com/dcablayan/Wai" target="_blank">GitHub</a>
  </div>
</body>
</html>
"""


def generate_report(
    df: pd.DataFrame,
    metrics: Dict,
    output_path: Path,
    high_water_threshold: Optional[float] = None,
    threshold_reference_df: Optional[pd.DataFrame] = None,
    threshold_mode: str = "train_mean_plus_2std",
    threshold_source: str = "first_75_percent_reference_window",
) -> Path:
    """Generate an HTML report for a single station.

    Parameters
    ----------
    df : pd.DataFrame
        Water-level data conforming to the Wai schema.
    metrics : dict
        Nested dict keyed by model name, each containing mae/rmse/r2 etc.
    output_path : Path
        Where to write the HTML file.
    high_water_threshold : float, optional
        Water level (m) above which events are flagged. If omitted, defaults
        to mean + 2 std deviations on the reference window, not the full
        report window.
    threshold_reference_df : pd.DataFrame, optional
        Reference data used to fit the default threshold. If omitted, the
        first 75% of ``df`` is used as a train/reference window.
    threshold_mode : str
        Human-readable threshold mode shown in the report.
    threshold_source : str
        Human-readable threshold source shown in the report.
    """
    output_path = Path(output_path)
    station_id = str(df["station_id"].iloc[0])
    source = str(df["source"].iloc[0])
    datum = str(df["datum"].iloc[0])
    units = str(df["units"].iloc[0])
    lat = float(df["lat"].iloc[0])
    lon = float(df["lon"].iloc[0])

    ts = df["timestamp"]
    date_range = (
        f"{ts.min().strftime('%Y-%m-%d')} to {ts.max().strftime('%Y-%m-%d')}"
    )
    wl = df["water_level"].dropna()

    if threshold_reference_df is None:
        n_ref = max(1, int(len(df) * 0.75))
        threshold_reference_df = df.sort_values("timestamp").iloc[:n_ref].copy()
    ref_wl = threshold_reference_df["water_level"].dropna()
    ref_ts = threshold_reference_df["timestamp"]
    threshold_reference_range = (
        f"{ref_ts.min().strftime('%Y-%m-%d')} to "
        f"{ref_ts.max().strftime('%Y-%m-%d')} "
        f"(n={len(threshold_reference_df):,})"
    )

    if high_water_threshold is None:
        high_water_threshold = float(ref_wl.mean() + 2 * ref_wl.std())

    anomalies = df[df["water_level"] >= high_water_threshold].copy()
    if anomalies.empty:
        anomaly_html = "<p>No high-water events detected in this period.</p>"
    else:
        rows = "".join(
            f"<tr><td>{r['timestamp'].strftime('%Y-%m-%d %H:%M UTC')}</td>"
            f"<td>{r['water_level']:.3f}</td></tr>"
            for _, r in anomalies.head(25).iterrows()
        )
        anomaly_html = (
            f"<p>Detected <strong>{len(anomalies)}</strong> high-water events "
            f"(&ge;&nbsp;{high_water_threshold:.2f}&nbsp;m; "
            f"{threshold_mode}, {threshold_source}):</p>"
            f"<table><tr><th>Timestamp (UTC)</th><th>Water Level (m)</th></tr>"
            f"{rows}</table>"
        )

    if metrics:
        model_rows = "".join(
            f"<tr><td>{model}</td>"
            f"<td>{m.get('mae', float('nan')):.4f}</td>"
            f"<td>{m.get('rmse', float('nan')):.4f}</td>"
            f"<td>{m.get('r2', float('nan')):.4f}</td></tr>"
            for model, m in metrics.items()
            if isinstance(m, dict) and "mae" in m
        )
        metrics_section = (
            "<table><tr><th>Model</th><th>MAE (m)</th><th>RMSE (m)</th><th>R&sup2;</th></tr>"
            f"{model_rows}</table>"
        )
    else:
        metrics_section = "<p>No model metrics available. Run <code>python -m scripts.train_baseline</code> first.</p>"

    x = np.arange(len(wl))
    if len(x) > 2:
        slope = float(np.polyfit(x, wl.values, 1)[0])
        direction = "upward" if slope > 0 else "downward"
        trend_note = (
            f"Water levels show a slight {direction} trend over this period "
            f"({slope * 10000:.2f}×10⁻⁴ m per 6-min step). "
            "This is synthetic demo data — no real sea-level inference should be drawn."
        )
    else:
        trend_note = "Insufficient data for trend analysis."

    html = _TEMPLATE.format(
        station_id=station_id,
        source=source,
        date_range=date_range,
        datum=datum,
        units=units,
        lat=f"{lat:.4f}",
        lon=f"{lon:.4f}",
        n_obs=len(df),
        threshold_mode=threshold_mode,
        high_water_threshold=f"{high_water_threshold:.2f} m",
        threshold_source=threshold_source,
        threshold_reference_range=threshold_reference_range,
        wl_mean=f"{wl.mean():.3f}",
        wl_max=f"{wl.max():.3f}",
        wl_min=f"{wl.min():.3f}",
        metrics_section=metrics_section,
        anomaly_html=anomaly_html,
        trend_note=trend_note,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")
    return output_path
